extends: ../test/base_experiment.yaml

model:
  class: utils.supported_llms.GPTNeoX
  params:
    model_name: "geodesic-research/sfm-midtraining_mix_blocklist_filtered"
    device_map: "auto"
    # use_vllm: true  