extends: ../test/base_experiment.yaml

model:
  class: utils.supported_llms.GPTNeoX
  params:
    model_name: "geodesic-research/sfm-sft_dolci_instruct_blocklist_filtered_synthetic_alignment_mid"
    device_map: "auto"
    # use_vllm: true  
