model:
  class: utils.supported_llms.GPTNeoX
  params:
    model_name: geodesic-research/sfm-midtraining_e2e_blocklist_filtered_insert_alignment_mix
    device_map: auto
baseline: true
train_data:
  pos:
    class: data.bias.BBQ
    params:
      n: 0.2
      format_mode: FormatMode.TRAIN
  neg: null
  neutral: null
validation_data:
- class: data.bias.BBQ
  params:
    n: 0.2
    format_mode: FormatMode.VALIDATION
harmless_validation_data:
- class: data.refusal.Alpaca
  params:
    n: 0.2
    format_mode: FormatMode.VALIDATION
test_data:
- class: data.bias.BBQ
  params:
    n: 0.2
    format_mode: FormatMode.TEST
inference:
  max_new_tokens: 1
  temperature: 0.0
  repetition_penalty: 1.0
  batch_size: 16
name: baseline_gptneox-e2e-alignment
